events { 
    worker_connections 1024; 
}

http {
    # SERVER 1: HTTP (Port 80)
    server {
        listen 80;
        server_name movie-trip.kurangdoa.com localhost;

        # Certbot validation path
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        # Redirect everything else to HTTPS
        location / {
            return 301 https://movie-trip.kurangdoa.com$request_uri;;
        }
    }

#     # SERVER 2: HTTPS (Port 443) - This is where the magic happens
#     server {
#         listen 443 ssl;
#         server_name movie-trip.kurangdoa.com;

#         # These paths must match where you store the Porkbun or Certbot files
#         ssl_certificate /etc/letsencrypt/live/movie-trip.kurangdoa.com/fullchain.pem;
#         ssl_certificate_key /etc/letsencrypt/live/movie-trip.kurangdoa.com/privkey.pem;

#         # Route /api/ to your FastAPI Backend
#         location /api/ {
#             proxy_pass http://backend:8000/api/;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#         }

#         # Route /docs for Swagger UI
#         location /docs {
#             proxy_pass http://backend:8000/docs;
#         }

#         # Route everything else to the Next.js Frontend
#         location / {
#             proxy_pass http://frontend:3000/;
#             proxy_set_header Host $host;
#             proxy_set_header X-Real-IP $remote_addr;
#         }
    # }
}
